parameters:
 - name: succeed
   displayName: Succeed or Fail
   type: boolean
   default: false

trigger:
- main

pool:
 vmImage: ubuntu-latest

jobs:
  - job: work
    steps:
     - script: echo Hello World
       displayName: 'Run a one line script'
    - script: git clone malinformed
      condition: eq(${{parameters.succeed}})
  - job: ErrorHandler
    dependson: Work
    condition: failed()
    steps:
      - bash: |
          az boards work-item create \
            --title "Build $(build.buildNumber) failed" \
            --type bug \
            --org $(System.TeamFoundationCollectionUri) \
            --project $(System.TeamProject)
        env: 
          AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
        displayName: 'Create work item on failure'